# Generated by Django 4.0.2 on 2022-02-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bid_types',
            },
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('count', models.IntegerField()),
                ('created_at', models.DateField()),
                ('bid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='biddings.bidtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='products.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='users.user')),
            ],
            options={
                'db_table': 'biddings',
            },
        ),
    ]
